config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :fields
  
  
  root to: 'pages#home'
  get 'pages/error', to: 'pages#error'
  get '/:profile', to: 'profile#index', as: :user
  # post '/:profile', to: 'profile#appointments'
  get '/:profile/new', to: 'appointments#new'
  post '/:profile/new', to: 'appointments#create'

  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :user, :optional => true
    belongs_to :field
end

app/models/field.rb
class Field < ApplicationRecord
    has_many :appoitments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :appointments, :dependent => :nullify
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]
  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
 
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
    @field = Field.all
    @user = User.all
  end

  # GET /appointments/1/edit
  def edit
    @field = Field.all
    @user = User.all
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    @field = Field.all
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    if current_user.admin
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  else 
    if @appointment.user_id == current_user.id
      respond_to do |format|
        if @appointment.update(appointment_params)
          format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
          format.json { render :show, status: :ok, location: @appointment }
        else
          format.html { render :edit }
          format.json { render json: @appointment.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to '/pages/error'
    end

  end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    if current_user.admin
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  else 
    if @appointment.user_id == current_user.id
      @appointment.destroy
     redirect_to appointments_url, notice: 'Appointment was successfully destroyed.'
       
      else
        redirect_to 'pages/error'
   
  end
end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:title, :description, :start_time, :end_time, :user_id, :field_id)
    end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:show, :edit, :update, :destroy]

  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1
  # GET /fields/1.json
 
  def show
  end

  # GET /fields/new
  def new
    if current_user.admin
    @field = Field.new
    else
      redirect_to 'pages/error'
  end
end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    if current_user.admin
    @field = Field.new(field_params)

    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  else
    redirect_to 'pages/error'
  end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    if current_user.admin
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  else
    redirect_to 'pages/error'

  end
  
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    if current_user.admin
    @field.destroy
    respond_to do |format|
      format.html { redirect_to fields_url, notice: 'Field was successfully destroyed.' }
      format.json { head :no_content }
    end
  else
    redirect_to 'pages/error'

  end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:name, :description, :open, :close, :street, :city, :state, :zip)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def error
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
    before_action :set_profile, only: [:index, :new, :create]
    def index
      if @profile
        @appointment = @profile.appointments.order 'created_at desc'
      end

    end
  
    def new
    end
  
    
  
    private
      def set_profile
        @profile = User.find_by(name: params[:profile])
      end
  
   
  end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def sign_up_params
        params.require(:user).permit(:email,:password, :password_confirmation, :name, :last_name, :phone)
     
      end
     
      def account_update_params
        params.require(:user).permit(:email,:password, :password_confirmation, :current_password, :name, :last_name, :phone)
      end
     
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/appoitments_helper.rb
module AppoitmentsHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/appointments/_form.html.erb
<div>
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field " >
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <% form.label :field_id%> Field: 
<%= form.select(:field_id) do %>
                <% @field.order('name ASC').each do |field_select| %>
                  <%= content_tag(:option, field_select.name, value: field_select.id) %>
                <% end %>
            <% end %>
           
  </div>


  <div class="field">
    <%= form.label :confirm_your_name %>
   
      <%= form.select(:user_id) do %>
                <% @user.order('last_name ASC').each do |user_select| %>
                  <%= content_tag(:option, user_select.last_name, value: user_select.id) %>
                <% end %>
            <% end %>
  </div>

  <div class="actions">
    <%= form.submit :class=>"btn btn-info" %>
    <%= link_to 'Back', appointments_path, :class=>"btn btn-info", :id=>"reload" %>
  </div>
<% end %>
</div>

app/views/appointments/edit.html.erb
<div class="for">
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>



</div>

app/views/appointments/index.html.erb
<p id="notice"><%= notice %></p>
<div class="appo">

<div class="apptable">

<h1>Appointments</h1>
<%= link_to new_appointment_path do %>
<button type="button" class="btn btn-info">Schedule a play time
<i class="fas fa-plus"></i>
</button>
<%end%>
<table>
  <thead>
    <tr>
      <th>Title</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.title %></td>
      
        <td> <a href="/appointments/<%=appointment.id%>">
       
        <i class="far fa-eye"></i></a>
        </td>
        <% if current_user%>
        <td><a href="/appointments/<%=appointment.id%>/edit"
        <i class="far fa-edit"></i></a>
      
       </td>
      
      
        <td><%= link_to appointment, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="far fa-trash-alt"></i>
        <%end%>
        </td>
         <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>


<div id="calendar" ></div>

</div>

app/views/appointments/new.html.erb
<div class="for">
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>


</div>

app/views/appointments/show.html.erb
<div id="form">
<p>
  <strong>Title:</strong>
  <%= @appointment.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @appointment.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @appointment.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @appointment.end_time %>
</p>

 <%if !current_user%>
<%= link_to 'Back', appointments_path %>
<%elsif current_user.admin%>
<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

 <%elsif current_user.id == @appointment.id%>
  <%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>
 
<%end%>
</div>

app/views/appoitments/_form.html.erb
<%= form_with(model: appoitment, local: true) do |form| %>
  <% if appoitment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appoitment.errors.count, "error") %> prohibited this appoitment from being saved:</h2>

      <ul>
      <% appoitment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :field_id %>
    <%= form.number_field :field_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/fields/_form.html.erb
<div >
<%= form_with(model: field, local: true) do |form| %>
  <% if field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
      <% field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

   <div class="field">
    <%= form.label :open_from %>
    <%= form.time_field :open %>
    <%= form.label :to %>
    <%= form.time_field :close %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.label :street %>
    <%= form.text_field :street %>
    <%= form.label :city %>
    <%= form.text_field :city %>
    <%= form.label :state %>
    <%= form.text_field :state %>
    <%= form.label :zip %>
    <%= form.number_field :zip %>
  </div>

  <div class="actions">
    <%= form.submit :class=>"btn btn-info" %>
    <%= link_to 'Back', fields_path, :class=>"btn btn-info" %>
  </div>
<% end %>
</div>

app/views/fields/edit.html.erb
<div class="for">
<h1>Editing Field</h1>

<%= render 'form', field: @field %>



</div>

app/views/fields/index.html.erb
<p id="notice"><%= notice %></p>
<div id="profile">
<div id="form">
<h1>Fields</h1>
<%= link_to 'Add a new field', new_field_path , :class=>"btn btn-info"%>
<table>
  <thead>
    <tr>
      <th>Name</th>
      
      
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @fields.each do |field| %>
      <tr>
        <td><%= field.name %></td>
     
        <td><%= link_to field do %>
        <i class="far fa-eye"></i>
        <%end%>
        </td>
        <td><%= link_to edit_field_path(field) do %>
        <i class="far fa-edit"></i>
        <%end%>
        </td>
        <td><%= link_to field, method: :delete, data: { confirm: 'Are you sure?' } do%>
        <i class="far fa-trash-alt"></i>
        <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>
</div>

app/views/fields/new.html.erb
<div class="for">
<h1>New Field</h1>

<%= render 'form', field: @field %>

</div>

app/views/fields/show.html.erb
<div id="form">
<p>
  <strong>Name:</strong>
  <%= @field.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @field.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @field.street %>
  <%= @field.city %>
  <%= @field.state %>
  <%= @field.zip %>
</p>

<p>
  <strong>Open</strong>
  <%= @field.open%>
</p>

<p>
  <strong>Close</strong>
  <%= @field.close%>
</p>

<%= link_to 'Edit', edit_field_path(@field), :class=>"btn btn-info" %> 
<%= link_to 'Back', fields_path, :class=>"btn btn-info" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BobiScheduler</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
      <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  
 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
   
  
   
    <link src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ui-bootstrap/0.5pre/assets/css/bootstrap.min.css">
    
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <%= stylesheet_link_tag    'fullcalendar', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        

      
      <header class="ui top fixed menu">
      <div class="top-nav">
      <a class="lin" href="/"><h1 id="logo">B <span><img src="https://media.giphy.com/media/c6VvvRLR3aIIKxiYdD/giphy.gif" id="ball" style="position: absolute; height:70px;
        
       
        <%# margin-left: 1166px; %>
        animation: run 20s normal;"></span> <span id="logobi">BI</span></h1></a>
      <%# <img src="https://media.giphy.com/media/c6VvvRLR3aIIKxiYdD/giphy.gif" id="ball" style="position: absolute;
        
       
        <%# margin-left: 1166px; %>
        <%# animation: run 20s normal;"> %> 
        <div>
      <% if !current_user %>
            <a id="reload" href="/appointments"><button class="btn btn-info">Appointments</button></a>
            <a href="/users/sign_in"><button class="btn btn-info">Sign in</button></a>
           
            <a href="/users/sign_up"><button class="btn btn-info">Sign up</button></a>

       
        <%else%>
            <a id="reload"href="/appointments"><button class="btn btn-info">Appointments</button></a>
            <a href="/<%=current_user.name%>"><button class="btn btn-info">Profile</button></a>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete , :class => "btn btn-info"%>
            
      
      <% end %>
      </div>
      </div>
        </header>
         <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    
       <footer>
       <div id="contact">
        <h3>Contact</h3>
        <p>Phone: +383 44 814 814 </p>
        </div>
       </footer>
      <%# <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.3/semantic.min.js"></script> %>
     
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/1.20.3/TweenMax.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/ScrollMagic.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.js"> </script>
       <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/animation.gsap.js"></script>
  </body>
   <script>
 document.getElementById('reload').addEventListener('click', (e)=>{
            window.location.reload()
        })
  </script>
</html>

app/views/pages/error.html.erb
<div id="error">

    <img src="https://cdn.dribbble.com/users/1191144/screenshots/3544235/monster-gif.gif" alt="error">

</div>

app/views/pages/home.html.erb
<div id="pinContainer">

						<section class="panel blue">
                        <%if !current_user%>
                            <a href="/users/sign_up" id="getstarted"><button class="btn btn-info">Get started</button></a>
                            <%end%>
                            <img id="img1"src="https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/35389348_178886662795908_506454705229004800_n.jpg?_nc_cat=0&oh=c696f56f56508c85c3dec5aca3634026&oe=5C21378E">
                           
                        </section>
						<section class="panel turqoise">
							
                            <img id="img2" src="https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/37250648_201818063836101_4823638402467364864_n.jpg?_nc_cat=0&oh=0f62a4daa7c5a1c8d44edeb57c76d26e&oe=5C23F545">
						</section>
						<section class="panel green">
						
                            <img id="img3" src="https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/35481287_178886686129239_6756783391187664896_n.jpg?_nc_cat=0&oh=9e2cb6b9d562163451fc02de075457ee&oe=5C61C8AD">
						</section>
						<section class="panel bordeaux">
					
                            <img id="img4" src="https://scontent-lga3-1.xx.fbcdn.net/v/t1.0-9/37275270_201818057169435_1121116704844283904_n.jpg?_nc_cat=0&oh=c1e4f612c0dbed9a465fdf9d1ffbca04&oe=5C166A77">
						</section>
					</div>
                    <div class='content'>
                    <div class="hometext">
                     <h1 class="title">How we started!</h1>
                    <div class='about'>
                   <img class="sallaimg" src="<%= asset_url('howwestarted.jpg') %>">
                   <p  class="homepara">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                    </div>
                    </div>

                    <div class="hometext">

                     <h1 class="title">Where we at now</h1>

                     <div class='about'>
                     <p class="homepara">
                     
                    Nunc pulvinar sapien et ligula. Etiam erat velit scelerisque in dictum non consectetur a. In iaculis nunc sed augue lacus. Magna fermentum iaculis eu non diam phasellus vestibulum lorem. Pellentesque habitant morbi tristique senectus et. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. At volutpat diam ut venenatis tellus. Quam viverra orci sagittis eu volutpat odio. Lorem sed risus ultricies tristique nulla aliquet enim tortor at. Nunc sed blandit libero volutpat. Mi bibendum neque egestas congue quisque egestas. Vitae nunc sed velit dignissim sodales ut eu sem integer.
                    </p>
                    <img class="sallaimg" src="<%= asset_url('new.jpg') %>">
                     </div>
                    </div>
                    </div>